steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaBuildTool: 'classic'
  neoDeploy:
    deployMode: mta
    neo:
      credentialsId: 'neo_deploy'
      account: 's7am47zded'
      host: 'eu1.hana.ondemand.com'
